version: "3.8"
services:
  api:
    build:
      context: ./api
    container_name: api_c
    ports:
      - "3000:3000"
    volumes:
      #map all
      - ./api:/app
      #ignore node_modules
      - /app/node_modules
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui_c
    ports:
      - "5173:5173"
    volumes:
      #map all
      - ./ui/src:/app
      #ignore node_modules
      - /app/node_modules
    stdin_open: true
    tty: true
